In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from __future__ import division
from scipy.io import arff
from numpy import array
import numpy as np
import pandas as pd

#Read the train dataset from csv file
data, meta = arff.loadarff("weather.arff")
print(data)
print(meta)

[(b'sunny', 85., 85., b'FALSE', b'no')
 (b'sunny', 80., 90., b'TRUE', b'no')
 (b'overcast', 83., 86., b'FALSE', b'yes')
 (b'rainy', 70., 96., b'FALSE', b'yes')
 (b'rainy', 68., 80., b'FALSE', b'yes')
 (b'rainy', 65., 70., b'TRUE', b'no')
 (b'overcast', 64., 65., b'TRUE', b'yes')
 (b'sunny', 72., 95., b'FALSE', b'no')
 (b'sunny', 69., 70., b'FALSE', b'yes')
 (b'rainy', 75., 80., b'FALSE', b'yes')
 (b'sunny', 75., 70., b'TRUE', b'yes')
 (b'overcast', 72., 90., b'TRUE', b'yes')
 (b'overcast', 81., 75., b'FALSE', b'yes')
 (b'rainy', 71., 91., b'TRUE', b'no')]
Dataset: weather
	outlook's type is nominal, range is ('sunny', 'overcast', 'rainy')
	temperature's type is numeric
	humidity's type is numeric
	windy's type is nominal, range is ('TRUE', 'FALSE')
	play's type is nominal, range is ('yes', 'no')



In [3]:
from sklearn.preprocessing import LabelEncoder

train_csv = pd.read_csv("weather.csv",header=0)
array = np.array(train_csv)
X = array[:,:-1]
le = LabelEncoder()
A = le.fit_transform(X[:,0])
B = le.fit_transform(X[:,-1])
y = le.fit_transform(array[:,-1])
for i in range(0,len(X)):
    X[i,0] = A[i]
    X[i,-1] = B[i]
    
print(X)
print(y)

[[2 85 85 0]
 [2 80 90 1]
 [0 83 86 0]
 [1 70 96 0]
 [1 68 80 0]
 [1 65 70 1]
 [0 64 65 1]
 [2 72 95 0]
 [2 69 70 0]
 [1 75 80 0]
 [2 75 70 1]
 [0 72 90 1]
 [0 81 75 0]
 [1 71 91 1]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

X_train

array([[0, 81, 75, 0],
       [0, 64, 65, 1],
       [2, 69, 70, 0],
       [0, 83, 86, 0],
       [2, 75, 70, 1],
       [1, 65, 70, 1],
       [0, 72, 90, 1],
       [1, 71, 91, 1],
       [2, 80, 90, 1],
       [2, 85, 85, 0],
       [1, 68, 80, 0],
       [1, 75, 80, 0]], dtype=object)

In [5]:
print (len(X[0]))

4


In [6]:
model = Sequential()
model.add(Dense(units=100, activation='sigmoid'))
model.add(Dense(units=2, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])
# model.fit(X, y, epochs=150, batch_size=10,validation_split=0.1)
model.fit(X_train, y_train, batch_size=10, epochs=150)

Epoch 1/150
12/12 [==============================] - 0s 19ms/step - loss: 0.2693 - acc: 0.0000e+00
Epoch 2/150
12/12 [==============================] - 0s 1ms/step - loss: 0.2527 - acc: 0.0000e+00
Epoch 3/150
12/12 [==============================] - 0s 751us/step - loss: 0.2442 - acc: 0.0000e+00
Epoch 4/150
12/12 [==============================] - 0s 751us/step - loss: 0.2390 - acc: 0.0000e+00
Epoch 5/150
12/12 [==============================] - 0s 1ms/step - loss: 0.2352 - acc: 0.0000e+00
Epoch 6/150
12/12 [==============================] - 0s 583us/step - loss: 0.2320 - acc: 0.0000e+00
Epoch 7/150
12/12 [==============================] - 0s 751us/step - loss: 0.2273 - acc: 0.0000e+00
Epoch 8/150
12/12 [==============================] - 0s 667us/step - loss: 0.2242 - acc: 0.0000e+00
Epoch 9/150
12/12 [==============================] - 0s 750us/step - loss: 0.2220 - acc: 0.0000e+00
Epoch 10/150
12/12 [==============================] - 0s 667us/step - loss: 0.2213 - acc: 0.0000e+00
Epoc

12/12 [==============================] - 0s 417us/step - loss: 0.2116 - acc: 0.8333
Epoch 85/150
12/12 [==============================] - 0s 500us/step - loss: 0.2118 - acc: 0.8333
Epoch 86/150
12/12 [==============================] - 0s 500us/step - loss: 0.2119 - acc: 0.8333
Epoch 87/150
12/12 [==============================] - 0s 417us/step - loss: 0.2119 - acc: 0.8333
Epoch 88/150
12/12 [==============================] - 0s 417us/step - loss: 0.2105 - acc: 0.5000
Epoch 89/150
12/12 [==============================] - 0s 500us/step - loss: 0.2103 - acc: 0.3333
Epoch 90/150
12/12 [==============================] - 0s 417us/step - loss: 0.2105 - acc: 0.5000
Epoch 91/150
12/12 [==============================] - 0s 417us/step - loss: 0.2104 - acc: 0.3333
Epoch 92/150
12/12 [==============================] - 0s 500us/step - loss: 0.2105 - acc: 0.2500
Epoch 93/150
12/12 [==============================] - 0s 500us/step - loss: 0.2102 - acc: 0.3333
Epoch 94/150
12/12 [=======================

In [7]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print (val_loss, val_acc)

2/2 [==============================] - 0s 95ms/step
0.2587190866470337 1.0
