In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [5]:
from __future__ import division
from scipy.io import arff
from numpy import array
import numpy as np
import pandas as pd

#Read the train dataset from csv file
data, meta = arff.loadarff("weather.arff")
print(data)
print(meta)

[(b'sunny', 85., 85., b'FALSE', b'no')
 (b'sunny', 80., 90., b'TRUE', b'no')
 (b'overcast', 83., 86., b'FALSE', b'yes')
 (b'rainy', 70., 96., b'FALSE', b'yes')
 (b'rainy', 68., 80., b'FALSE', b'yes')
 (b'rainy', 65., 70., b'TRUE', b'no')
 (b'overcast', 64., 65., b'TRUE', b'yes')
 (b'sunny', 72., 95., b'FALSE', b'no')
 (b'sunny', 69., 70., b'FALSE', b'yes')
 (b'rainy', 75., 80., b'FALSE', b'yes')
 (b'sunny', 75., 70., b'TRUE', b'yes')
 (b'overcast', 72., 90., b'TRUE', b'yes')
 (b'overcast', 81., 75., b'FALSE', b'yes')
 (b'rainy', 71., 91., b'TRUE', b'no')]
Dataset: weather
	outlook's type is nominal, range is ('sunny', 'overcast', 'rainy')
	temperature's type is numeric
	humidity's type is numeric
	windy's type is nominal, range is ('TRUE', 'FALSE')
	play's type is nominal, range is ('yes', 'no')



In [6]:
from sklearn.preprocessing import LabelEncoder

train_csv = pd.read_csv("weather.csv",header=0)
array = np.array(train_csv)
X = array[:,:-1]
le = LabelEncoder()
A = le.fit_transform(X[:,0])
B = le.fit_transform(X[:,-1])
y = le.fit_transform(array[:,-1])
for i in range(0,len(X)):
    X[i,0] = A[i]
    X[i,-1] = B[i]
    
print(X)
print(y)

[[2 85 85 0]
 [2 80 90 1]
 [0 83 86 0]
 [1 70 96 0]
 [1 68 80 0]
 [1 65 70 1]
 [0 64 65 1]
 [2 72 95 0]
 [2 69 70 0]
 [1 75 80 0]
 [2 75 70 1]
 [0 72 90 1]
 [0 81 75 0]
 [1 71 91 1]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

X_train

array([[0, 81, 75, 0],
       [0, 64, 65, 1],
       [2, 69, 70, 0],
       [0, 83, 86, 0],
       [2, 75, 70, 1],
       [1, 65, 70, 1],
       [0, 72, 90, 1],
       [1, 71, 91, 1],
       [2, 80, 90, 1],
       [2, 85, 85, 0],
       [1, 68, 80, 0],
       [1, 75, 80, 0]], dtype=object)

In [14]:
y_train

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1], dtype=int64)

In [23]:
model = Sequential()
model.add(Dense(units=100, activation='sigmoid'))
model.add(Dense(units=2, activation='sigmoid'))

model.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])
# model.fit(X, y, epochs=150, batch_size=10,validation_split=0.1)
model.fit(X_train, y_train, batch_size=12, epochs=150)

Epoch 1/150
12/12 [==============================] - 0s 23ms/step - loss: 0.2574 - acc: 1.0000
Epoch 2/150
12/12 [==============================] - 0s 251us/step - loss: 0.2559 - acc: 1.0000
Epoch 3/150
12/12 [==============================] - 0s 167us/step - loss: 0.2545 - acc: 1.0000
Epoch 4/150
12/12 [==============================] - 0s 251us/step - loss: 0.2530 - acc: 1.0000
Epoch 5/150
12/12 [==============================] - 0s 333us/step - loss: 0.2515 - acc: 1.0000
Epoch 6/150
12/12 [==============================] - 0s 250us/step - loss: 0.2501 - acc: 1.0000
Epoch 7/150
12/12 [==============================] - 0s 250us/step - loss: 0.2486 - acc: 1.0000
Epoch 8/150
12/12 [==============================] - 0s 167us/step - loss: 0.2472 - acc: 1.0000
Epoch 9/150
12/12 [==============================] - 0s 250us/step - loss: 0.2458 - acc: 1.0000
Epoch 10/150
12/12 [==============================] - 0s 417us/step - loss: 0.2444 - acc: 0.9167
Epoch 11/150
12/12 [====================

Epoch 86/150
12/12 [==============================] - 0s 333us/step - loss: 0.2140 - acc: 0.9167
Epoch 87/150
12/12 [==============================] - 0s 250us/step - loss: 0.2139 - acc: 0.9167
Epoch 88/150
12/12 [==============================] - 0s 250us/step - loss: 0.2139 - acc: 0.9167
Epoch 89/150
12/12 [==============================] - 0s 250us/step - loss: 0.2138 - acc: 0.9167
Epoch 90/150
12/12 [==============================] - 0s 167us/step - loss: 0.2138 - acc: 0.9167
Epoch 91/150
12/12 [==============================] - 0s 250us/step - loss: 0.2137 - acc: 0.9167
Epoch 92/150
12/12 [==============================] - 0s 250us/step - loss: 0.2137 - acc: 0.9167
Epoch 93/150
12/12 [==============================] - 0s 250us/step - loss: 0.2137 - acc: 0.9167
Epoch 94/150
12/12 [==============================] - 0s 167us/step - loss: 0.2136 - acc: 0.9167
Epoch 95/150
12/12 [==============================] - 0s 250us/step - loss: 0.2136 - acc: 0.9167
Epoch 96/150
12/12 [==========

In [10]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print (val_loss, val_acc)

2/2 [==============================] - 0s 111ms/step
0.255665123462677 0.0


In [26]:
# Classifier by Python (nn)

from nn import NeuralNetwork

import numpy as np
import math

X = np.array([[0, 81, 75, 0],
       [0, 64, 65, 1],
       [2, 69, 70, 0],
       [0, 83, 86, 0],
       [2, 75, 70, 1],
       [1, 65, 70, 1],
       [0, 72, 90, 1],
       [1, 71, 91, 1],
       [2, 80, 90, 1],
       [2, 85, 85, 0],
       [1, 68, 80, 0],
       [1, 75, 80, 0]])
y = np.array([[1], [1], [1], [1], [1], [0], [1], [0], [0], [0], [1], [1]])

nn = NeuralNetwork(X,y)
nn.add(7)
nn.add(5)
nn.add(6)
nn.add(2)
nn.add(3)

nn.fit(12,150,0.5,0.001)

0.11775523780701275
0.11314464109448334
0.10872782227510897
0.1044973561108395
0.10044974344417841
0.15707937418721238
0.10133156597473404
0.1560210477545987
0.15011961014861022
0.14439648853377654
0.11187890629994074
0.10750170927477017
0.10331995104681685
0.0993202210969951
0.09549805378348142
0.09184838546048711
0.0883656932659616
0.1726265755364456
0.08957060302800633
0.17101126813137782
0.16473723602693466
0.1586155314925004
0.10011272623578941
0.09624270609278661
0.09255557293993937
0.08903686190246783
0.08568075923619335
0.08248118409089225
0.07943189229748059
0.18530652201745448
0.08082777127073039
0.1832640910746017
0.17675218093754666
0.17036526788680248
0.09120702818523478
0.08773876779164021
0.08443958133010233
0.08129486766327244
0.07829833162433973
0.0754436162741823
0.07272437720687354
0.19560973908162596
0.07423095247254033
0.1932450070108698
0.18658443219028018
0.18002347484394685
0.08438527424913782
0.08123207537339616
0.07823518328769816
0.07538028245941485
0.0726610

0.04620154191632898
0.24551328288756671
0.04783594420810098
0.24191777276184034
0.23489625874150943
0.22783351179126707
0.05630042034410646
0.05439737206371955
0.05259110951035174
0.0508708679721809
0.04923185298465802
0.04766952592432216
0.0461796014286987
0.24556566513580705
0.047815579414865646
0.2419656004490509
0.23493709318124892
0.22786718570820655
0.05628709003873533
0.05438276140521159
0.05257538671045328
0.05085418112486065
0.04921433602096329
0.04765129979501805
0.046160775219851034
0.24561094474796974
0.04779831627942307
0.24200651833138076
0.23497122117011437
0.22789438198321213
0.056276904591062576
0.0543712311771522
0.0525626811148466
0.05084044948424595
0.04919971358052593
0.04763590888439904
0.04614472635089371
0.24564986123387814
0.047783809930224165
0.24204126499661882
0.23499940615389592
0.22791588708844823
0.05626945510524852
0.05436239673297535
0.05255263072229354
0.0508293322441297
0.04918766469424873
0.047623050790453626
0.046131169800123474
0.24568303953558343


0.22753190175469853
0.05645100047085715
0.05454816553662158
0.052742658054997206
0.05102363757424627
0.04938624595842211
0.04782588785643727
0.04633822748170951
0.2451887043500526
0.047980687924491526
0.2415822449334137
0.23456668472023623
0.22751403565687453
0.05645473216840435
0.054554708335279235
0.05275175387161326
0.05103505686793525
0.04939977777804631
0.047841338538339724
0.04635541938636981
0.24514485724876153
0.047995750951567044
0.24154379302303028
0.23453880837391824
0.22749705508228624
0.05645768863866366
0.05456067374337666
0.05276045194569789
0.051046241885892456
0.04941322391547407
0.04785683847365393
0.046372782948041986
0.2451003634430653
0.04801082455293077
0.2415050430559632
0.23451126913373643
0.22748105150643486
0.05645982678293582
0.05456601798497105
0.0527687079944284
0.05105714798578939
0.04942653949771005
0.04787234267079108
0.04639027315353237
0.24505532844950725
0.04802586404626304
0.2414660973043962
0.23448416272897132
0.22746611347141202
0.05646110563267517

0.04679633999213104
0.24386430996621486
0.048286094972718276
0.2406040039001112
0.2342435044977447
0.22785639918298453
0.055943310335228175
0.05424104725873965
0.052618437267469474
0.05106656362931053
0.049581796064741356
0.048160683627035426
0.04679995400064115
0.24384602355900328
0.048283931093755006
0.24059812981781817
0.23426090660867968
0.22789728015929933
0.05591093591934457
0.05421591136440542
0.05259993352600691
0.05105415043533462
0.049574972030933744
0.048158984972562026
0.04680295201375622
0.24382912755343836
0.048281140536330376
0.24059364159432248
0.23427968784470152
0.22793952650121743
0.055877899727096746
0.0541901199812422
0.05258078218366977
0.051041098876502856
0.04956751997994371
0.048156669547511875
0.04680534521176282
0.2438136044554384
0.048277739906563
0.2405905110773485
0.23429980092265282
0.2279830718729997
0.05584424542014566
0.054163710475182286
0.05256101482806341
0.051027435225165625
0.04955946129874728
0.048153754252204396
0.04680714637785768
0.24379943298

0.051794086597244944
0.050438102018792036
0.04913396293481697
0.047879304968120116
0.046671872549933
0.24381591113097298
0.04797261883560256
0.2409523826782655
0.235340753668598
0.22970647174339312
0.054646402375631
0.05317964253061704
0.051773827419026065
0.05042200098130097
0.04912171315465188
0.047870620203496965
0.04666648594580134
0.24382132076963628
0.047963439019502695
0.2409656809710777
0.23536913005531315
0.22974997043979398
0.05461746725105444
0.05315545942609595
0.051754038138596366
0.05040628410194569
0.049109768643379355
0.04786216816512124
0.046661265401201045
0.24382648794820763
0.04795450904212666
0.24097856697107256
0.23539678077662884
0.22979242867772642
0.054589212167325186
0.05313185500765182
0.05173473439658385
0.05039096694843528
0.04909814484970152
0.047853964143064746
0.04665622601381664
0.24383137820325984
0.047945843883429935
0.24099100692610065
0.23542367302397024
0.22983381469270114
0.05456165146590684
0.05310884375755287
0.05171593074886228
0.05037606409174